# Test your FastAPI endpoints

GET http://127.0.0.1:8111/
Accept: application/json

###

POST http://127.0.0.1:8111//predict-sentiment
Content-Type: application/json

{
    "content": "tao ghét mày lắm"
}